name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Sprawdzenie kodu źródłowego
    - name: Checkout code
      uses: actions/checkout@v3

    # Ustawienie środowiska JDK
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17 # Upewnij się, że wersja JDK jest zgodna z projektem
        distribution: 'temurin'

    # Konfiguracja Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 31 # Wersja SDK (dopasuj do projektu)
        build-tools: 31.0.2
        ndk: false

    # Budowanie APK
    - name: Build APK
      run: ./gradlew assembleDebug # Zbudowanie wersji debug
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}

    # Zapisanie wyników (APK)
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
